'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 這類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建您的 VS 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強類型資源類別。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PhoneGap_xml_Generator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強類型資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查詢類似 &lt;access origin=&quot;*&quot; /&gt;
        '''    &lt;allow-intent href=&quot;http://*/*&quot; /&gt;
        '''    &lt;allow-intent href=&quot;https://*/*&quot; /&gt;
        '''    &lt;allow-intent href=&quot;tel:*&quot; /&gt;
        '''    &lt;allow-intent href=&quot;sms:*&quot; /&gt;
        '''    &lt;allow-intent href=&quot;mailto:*&quot; /&gt;
        '''    &lt;allow-intent href=&quot;geo:*&quot; /&gt; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property allow_intent() As String
            Get
                Return ResourceManager.GetString("allow_intent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 &lt;author email=&quot;%email%&quot; href=&quot;%website%&quot;&gt;
        '''%displayauthor%&lt;/author&gt; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property author() As String
            Get
                Return ResourceManager.GetString("author", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 &lt;content src=&quot;index.html&quot; /&gt; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property content() As String
            Get
                Return ResourceManager.GetString("content", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 &lt;description&gt;
        '''%description%&lt;/description&gt; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property description() As String
            Get
                Return ResourceManager.GetString("description", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 &lt;?xml version=&apos;1.0&apos; encoding=&apos;utf-8&apos;?&gt;
        '''&lt;widget id=&quot;%domain%&quot; version=&quot;1.0.0&quot; xmlns=&quot;http://www.w3.org/ns/widgets&quot; xmlns:gap=&quot;http://phonegap.com/ns/1.0&quot;&gt; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property initialize() As String
            Get
                Return ResourceManager.GetString("initialize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 &lt;name&gt;%name%&lt;/name&gt; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property name() As String
            Get
                Return ResourceManager.GetString("name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 &lt;platform name=&quot;android&quot;&gt;
        '''        &lt;icon density=&quot;ldpi&quot; src=&quot;www/res/icon/android/drawable-ldpi-icon.png&quot; /&gt;
        '''        &lt;icon density=&quot;mdpi&quot; src=&quot;www/res/icon/android/drawable-mdpi-icon.png&quot; /&gt;
        '''        &lt;icon density=&quot;hdpi&quot; src=&quot;www/res/icon/android/drawable-hdpi-icon.png&quot; /&gt;
        '''        &lt;icon density=&quot;xhdpi&quot; src=&quot;www/res/icon/android/drawable-xhdpi-icon.png&quot; /&gt;
        '''        &lt;icon density=&quot;xxhdpi&quot; src=&quot;www/res/icon/android/drawable-xxhdpi-icon.png&quot; /&gt;
        '''        &lt;icon density=&quot;xxxhdpi&quot; src=&quot;www/res/icon/android/drawable-xxx [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property platform_android() As String
            Get
                Return ResourceManager.GetString("platform_android", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 &lt;platform name=&quot;ios&quot;&gt;
        '''        &lt;icon height=&quot;57&quot; platform=&quot;ios&quot; src=&quot;www/res/icon/ios/icon.png&quot; width=&quot;57&quot; /&gt;
        '''        &lt;icon height=&quot;114&quot; platform=&quot;ios&quot; src=&quot;www/res/icon/ios/icon@2x.png&quot; width=&quot;114&quot; /&gt;
        '''        &lt;icon height=&quot;40&quot; platform=&quot;ios&quot; src=&quot;www/res/icon/ios/icon-40.png&quot; width=&quot;40&quot; /&gt;
        '''        &lt;icon height=&quot;80&quot; platform=&quot;ios&quot; src=&quot;www/res/icon/ios/icon-40@2x.png&quot; width=&quot;80&quot; /&gt;
        '''        &lt;icon height=&quot;50&quot; platform=&quot;ios&quot; src=&quot;www/res/icon/ios/icon-50.png&quot; width=&quot;50&quot; /&gt;
        '''        &lt;icon height=&quot;100&quot; platform=&quot;i [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property platform_ios() As String
            Get
                Return ResourceManager.GetString("platform_ios", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 &lt;platform name=&quot;android&quot;&gt;
        '''        &lt;allow-intent href=&quot;market:*&quot; /&gt;
        '''    &lt;/platform&gt;
        '''    &lt;platform name=&quot;ios&quot;&gt;
        '''        &lt;allow-intent href=&quot;itms:*&quot; /&gt;
        '''        &lt;allow-intent href=&quot;itms-apps:*&quot; /&gt;
        '''    &lt;/platform&gt;
        '''&lt;/widget&gt; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property platform_spec() As String
            Get
                Return ResourceManager.GetString("platform_spec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 &lt;platform name=&quot;windows&quot;&gt;
        '''        &lt;icon height=&quot;150&quot; platform=&quot;windows&quot; src=&quot;www/res/icon/windows/Square150x150Logo.scale-100.png&quot; width=&quot;150&quot; /&gt;
        '''        &lt;icon height=&quot;30&quot; platform=&quot;windows&quot; src=&quot;www/res/icon/windows/Square30x30Logo.scale-100.png&quot; width=&quot;30&quot; /&gt;
        '''        &lt;icon height=&quot;50&quot; platform=&quot;windows&quot; src=&quot;www/res/icon/windows/StoreLogo.scale-100.png&quot; width=&quot;50&quot; /&gt;
        '''        &lt;splash height=&quot;300&quot; platform=&quot;windows&quot; src=&quot;www/res/screen/windows/SplashScreen.scale-100.png&quot; width=&quot;620&quot; /&gt;
        '''        &lt;icon height= [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property platform_windows() As String
            Get
                Return ResourceManager.GetString("platform_windows", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 &lt;platform name=&quot;wp8&quot;&gt;
        '''        &lt;icon height=&quot;99&quot; platform=&quot;wp8&quot; src=&quot;www/res/icon/wp8/ApplicationIcon.png&quot; width=&quot;99&quot; /&gt;
        '''        &lt;icon height=&quot;159&quot; platform=&quot;wp8&quot; src=&quot;www/res/icon/wp8/Background.png&quot; width=&quot;159&quot; /&gt;
        '''        &lt;splash height=&quot;1280&quot; platform=&quot;wp8&quot; src=&quot;www/res/screen/wp8/screen-portrait.jpg&quot; width=&quot;768&quot; /&gt;
        '''    &lt;/platform&gt; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property platform_wp8() As String
            Get
                Return ResourceManager.GetString("platform_wp8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 &lt;plugin name=&quot;cordova-plugin-battery-status&quot; source=&quot;npm&quot; spec=&quot;~1.1.1&quot; /&gt;
        '''    &lt;plugin name=&quot;cordova-plugin-camera&quot; source=&quot;npm&quot; spec=&quot;~2.1.1&quot; /&gt;
        '''    &lt;plugin name=&quot;cordova-plugin-media-capture&quot; source=&quot;npm&quot; spec=&quot;~1.2.0&quot; /&gt;
        '''    &lt;plugin name=&quot;cordova-plugin-console&quot; source=&quot;npm&quot; spec=&quot;~1.0.2&quot; /&gt;
        '''    &lt;plugin name=&quot;cordova-plugin-contacts&quot; source=&quot;npm&quot; spec=&quot;~2.0.1&quot; /&gt;
        '''    &lt;plugin name=&quot;cordova-plugin-device&quot; source=&quot;npm&quot; spec=&quot;~1.1.1&quot; /&gt;
        '''    &lt;plugin name=&quot;cordova-plugin-device-motion&quot; source=&quot;npm&quot; spec=&quot;~1.2. [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property plugins() As String
            Get
                Return ResourceManager.GetString("plugins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 &lt;preference name=&quot;DisallowOverscroll&quot; value=&quot;%disoverscroll%&quot; /&gt;
        '''    &lt;preference name=&quot;android-minSdkVersion&quot; value=&quot;%sdkver%&quot; /&gt; 的當地語系化字串。
        '''</summary>
        Friend ReadOnly Property preference() As String
            Get
                Return ResourceManager.GetString("preference", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
